---
development:
  cloud_name: dwbb8wsd4
  api_key: '626169361421679'
  api_secret: 65XkO_c9vzoCddPkpXqWkzLhAIg
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dwbb8wsd4
  api_key: '626169361421679'
  api_secret: 65XkO_c9vzoCddPkpXqWkzLhAIg
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dwbb8wsd4
  api_key: '626169361421679'
  api_secret: 65XkO_c9vzoCddPkpXqWkzLhAIg
  enhance_image_tag: true
  static_image_support: false
